import { validateFeed } from "@opentechevents/validate";

import type { OteEvent, OteFeed, OteFeedConfig } from "./types.js";

export type {
  OteAttendanceMode,
  OteEvent,
  OteEventStatus,
  OteFeed,
  OteFeedConfig,
  OteGeo,
  OteLocation,
  OteSource,
} from "./types.js";

/** Spec version stamped on every assembled feed. Matches the vendored schema. */
export const SPEC_VERSION = "0.2.0";

/** One event file, already parsed. `file` is the path shown in error messages. */
export interface EventFileInput {
  file: string;
  json: unknown;
}

/** A build problem anchored to a source file and a field path within it. */
export interface BuildProblem {
  /** Source file the problem belongs to (e.g. "events/2026-06.json"). */
  file: string;
  /** Field path within that file, "(document)" for the whole document. */
  path: string;
  message: string;
}

export interface BuildFeedInput {
  /** Parsed ote.config.json. Only its `feed` block is consumed. */
  config: unknown;
  events: EventFileInput[];
  /** Feed `updatedAt` (ISO-8601 instant). Injected so the function stays pure. */
  now: string;
}

export type BuildFeedResult =
  | { ok: true; feed: OteFeed }
  | { ok: false; problems: BuildProblem[] };

const CONFIG_FILE = "ote.config.json";

/** Feed fields sourced from the config's `feed` block, in feed order. */
const FEED_CONFIG_FIELDS = [
  "title",
  "description",
  "url",
  "license",
  "licenseUrl",
] as const;

const REQUIRED_CONFIG_FIELDS = new Set(["title", "license"]);

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Structural read of the config's `feed` block. Presence and type only —
 * value constraints (license pattern, URL format…) come from the feed schema
 * once the feed is assembled, so they are never duplicated here.
 */
function readFeedConfig(
  config: unknown,
  problems: BuildProblem[],
): Partial<OteFeedConfig> {
  if (!isObject(config)) {
    problems.push({
      file: CONFIG_FILE,
      path: "(document)",
      message: "must be a JSON object",
    });
    return {};
  }
  const feed = config.feed;
  if (!isObject(feed)) {
    problems.push({
      file: CONFIG_FILE,
      path: "feed",
      message:
        'is missing: ote.config.json needs a "feed" object with at least "title" and "license"',
    });
    return {};
  }
  const out: Partial<OteFeedConfig> = {};
  for (const field of FEED_CONFIG_FIELDS) {
    const value = feed[field];
    if (value === undefined) {
      if (REQUIRED_CONFIG_FIELDS.has(field)) {
        problems.push({
          file: CONFIG_FILE,
          path: `feed.${field}`,
          message: "is required",
        });
      }
      continue;
    }
    if (typeof value !== "string") {
      problems.push({
        file: CONFIG_FILE,
        path: `feed.${field}`,
        message: "must be a string",
      });
      continue;
    }
    out[field] = value;
  }
  return out;
}

/** Sort key: startDate, then id, so the feed is stable across readdir order. */
function compareEvents(a: OteEvent, b: OteEvent): number {
  const byStart = String(a.startDate ?? "").localeCompare(
    String(b.startDate ?? ""),
  );
  if (byStart !== 0) return byStart;
  return String(a.id ?? "").localeCompare(String(b.id ?? ""));
}

/**
 * Maps a validation error on the assembled feed back to its source file:
 * `events[i].field` belongs to the i-th event file; top-level feed fields
 * belong to ote.config.json (as `feed.<field>`); anything else (specVersion,
 * updatedAt, events) is generated by this builder.
 */
function attribute(
  error: { path: string; message: string },
  files: string[],
): BuildProblem {
  const eventMatch = /^events\[(\d+)\]\.?(.*)$/.exec(error.path);
  if (eventMatch) {
    const file = files[Number(eventMatch[1])] ?? "(unknown event file)";
    return {
      file,
      path: eventMatch[2] || "(document)",
      message: error.message,
    };
  }
  const head = error.path.split(/[.[]/, 1)[0];
  if ((FEED_CONFIG_FIELDS as readonly string[]).includes(head)) {
    return {
      file: CONFIG_FILE,
      path: `feed.${error.path}`,
      message: error.message,
    };
  }
  return { file: "(assembled feed)", path: error.path, message: error.message };
}

/**
 * Assembles an OTE Feed (v0.2) from parsed event documents and the `feed`
 * block of ote.config.json, then validates the whole feed. Pure function:
 * reads no files, makes no network calls, takes the clock as `now`.
 *
 * Events inherit the feed's specVersion and license, so event files are NOT
 * validated standalone (that would wrongly demand a per-event license):
 * the assembled feed is validated once and every error is attributed back to
 * its source file and field. Events are sorted by startDate, then id.
 */
export function buildFeed(input: BuildFeedInput): BuildFeedResult {
  const problems: BuildProblem[] = [];
  const feedConfig = readFeedConfig(input.config, problems);

  const entries: Array<{ file: string; event: OteEvent }> = [];
  const seenIds = new Map<string, string>();
  for (const { file, json } of input.events) {
    if (!isObject(json)) {
      problems.push({
        file,
        path: "(document)",
        message: "must be a JSON object",
      });
      continue;
    }
    const event = json as unknown as OteEvent;
    entries.push({ file, event });
    // The schema cannot see across files: duplicate ids are checked here.
    if (typeof event.id === "string") {
      const previous = seenIds.get(event.id);
      if (previous) {
        problems.push({
          file,
          path: "id",
          message: `duplicates the id already used by ${previous}`,
        });
      } else {
        seenIds.set(event.id, file);
      }
    }
  }

  entries.sort((a, b) => compareEvents(a.event, b.event));

  const feedLicense = feedConfig.license ?? "missing-license";

  // Inherit-at-rest, materialise-on-publish: event files may omit specVersion
  // and license (the editor does, so authors never restate the feed's), but
  // every event in the PUBLISHED feed carries both, so a consumer reading a
  // single event out of the feed gets a self-contained document. An event's
  // own value wins (a per-event license may legitimately differ from the
  // feed's); only the absent ones are filled. Placed first so materialised
  // events lead with specVersion/license, like a standalone event document.
  const materialise = (event: OteEvent): OteEvent => ({
    specVersion: SPEC_VERSION,
    license: feedLicense,
    ...event,
  });

  // Placeholders keep feed validation running when the config is broken, so
  // event errors are still reported in the same pass. The placeholders
  // themselves are valid; the config problems above already fail the build.
  const feed: OteFeed = {
    specVersion: SPEC_VERSION,
    title: feedConfig.title ?? "(missing title)",
    ...(feedConfig.description !== undefined && {
      description: feedConfig.description,
    }),
    ...(feedConfig.url !== undefined && { url: feedConfig.url }),
    license: feedLicense,
    ...(feedConfig.licenseUrl !== undefined && {
      licenseUrl: feedConfig.licenseUrl,
    }),
    updatedAt: input.now,
    events: entries.map((e) => materialise(e.event)),
  };

  const result = validateFeed(feed);
  if (!result.valid) {
    const files = entries.map((e) => e.file);
    for (const error of result.errors) {
      problems.push(attribute(error, files));
    }
  }

  return problems.length > 0 ? { ok: false, problems } : { ok: true, feed };
}
