// Step script of the issue-to-pr.yml reusable workflow. Runs from the
// ote-tools checkout (`.ote-tools/`) after @opentechevents/validate is
// built, so validation is the exact same implementation the validate.yml
// workflow and the packages use.
//
// Reads the issue body, extracts the event JSON from EVERY fenced code
// block (one issue can propose several events at once — e.g. a recurring
// series generated by the OTE editor's "Submit all as one issue"),
// validates each against the OTE event schema and derives its
// events/<slug>.json filename. A plain event block (no `_oteBatchMode` key)
// behaves exactly as before (one block, one file) — this is additive, not
// a breaking change. A block may instead carry a top-level `_oteBatchMode`
// key (same "transient signal on the JSON payload" convention as
// `_localizeImages`, see localizeEventImages below) to unpack into several
// {event, slug} results from a much smaller wire payload:
//   "recurring-template" — {template, occurrences}: template merged with
//     each occurrence's own id/startDate/endDate override, one result per
//     occurrence. See apps/editor/src/lib/links.ts's recurringTemplateIssueBody.
//   "patch" — {slug, patch}: reads the existing events/<slug>.json from the
//     checkout, shallow-merges `patch` onto it (a `null` value deletes that
//     key), validates the merged result. Errors if the target file doesn't
//     exist — patch mode can only update an existing event, never create
//     one. See apps/editor/src/lib/links.ts's patchIssueBody.
//   "shared-patch" — {slugs, patch}: the same `patch` applied to every file
//     named in `slugs` — for when several documents receive the exact same
//     change (e.g. a bulk edit's shared template field with no per-
//     occurrence override), so that one value isn't repeated once per file.
//     A "patch"/"shared-patch" block targeting a slug that another such
//     block in the same issue also targets is not a duplicate-filename
//     error (unlike two full-document blocks) — their patches are merged
//     onto that one file in block order, last write per key wins. See
//     apps/editor/src/lib/links.ts's patchIssueBody.
//

// Env in:
//   ISSUE_BODY          full issue body
//   OTE_COMMENT_MARKER  hidden marker that identifies the workflow's comment
//   RUNNER_TEMP         directory for the result files
// Outputs (GITHUB_OUTPUT):
//   valid  "true" | "false"
//   count  number of events (only when valid)
// Files (in RUNNER_TEMP):
//   ote-events.json  [{event, slug}, ...], ready to commit (only when valid)
//   ote-comment.md   issue comment body (only when invalid — the success
//                    comment is written by the workflow, it needs the PR URL)

import { createHash } from "node:crypto";
import { lookup } from "node:dns/promises";
import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import net from "node:net";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { validateEventInFeed } from "../../packages/validate/dist/index.js";

// Slugs must be usable as a filename in events/ and in URLs we build.
// Mirrors apps/editor/src/lib/repo.ts (slugFromId) and
// apps/editor/src/lib/event-json.ts (suggestSlug) so the file lands where
// the editor expects it.
export const SLUG_RE = /^[A-Za-z0-9._-]+$/;
const FENCE_RE = /```[^\n]*\r?\n([\s\S]*?)\r?\n?```/g;

export function slugFromId(id) {
  if (typeof id !== "string") return null;
  let pathname;
  try {
    pathname = new URL(id).pathname;
  } catch {
    return null;
  }
  const segment = decodeURIComponent(
    pathname.split("/").filter(Boolean).at(-1) ?? "",
  );
  const slug = segment.endsWith(".json")
    ? segment.slice(0, -".json".length)
    : segment;
  return SLUG_RE.test(slug) ? slug : null;
}

export function suggestSlug(name, startDate) {
  const yearMonth = /^(\d{4}-\d{2})/.exec(startDate)?.[1];
  const kebab = String(name)
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  if (!kebab) return null;
  return yearMonth ? `${yearMonth}-${kebab}` : kebab;
}

/** Every fenced code block's inner text, in document order. */
export function extractFencedBlocks(body) {
  return [...body.matchAll(FENCE_RE)].map((m) => m[1]);
}

/** Thrown by parseIssueBody on the first problem — title + Markdown detail lines for the rejection comment. */
export class IssueToPrError extends Error {
  constructor(title, details) {
    super(title);
    this.title = title;
    this.details = details;
  }
}

function capitalize(label) {
  return `${label[0].toUpperCase()}${label.slice(1)}`;
}

/** Throws IssueToPrError unless `event` validates against the OTE event schema. */
function assertValidEvent(event, label) {
  // Feed context, not standalone: events/<slug>.json is a feed fragment that
  // inherits specVersion and license from the feed (same rules build-feed
  // --check applies — the editor deliberately omits both fields).
  const result = validateEventInFeed(event);
  if (!result.valid) {
    throw new IssueToPrError(
      `${capitalize(label)} is not valid against the OTE event schema`,
      result.errors.map((e) => `- \`${e.path}\` — ${e.message}`),
    );
  }
}

/** Derives the events/<slug>.json filename for `event`, or throws. */
function deriveSlug(event, label) {
  const slug = slugFromId(event.id) ?? suggestSlug(event.name, event.startDate);
  if (!slug) {
    throw new IssueToPrError(`Cannot derive a filename for ${label}`, [
      "The event is valid, but neither its `id` (last path segment) nor its",
      "`name` yields a filename-safe slug for `events/<slug>.json`.",
      "Give the `id` a final path segment matching `[A-Za-z0-9._-]+`.",
    ]);
  }
  return slug;
}

/**
 * Expands a `{_oteBatchMode: "recurring-template", template, occurrences}`
 * block into one {event, slug} per occurrence — `template` shallow-merged
 * with each occurrence's own id/startDate/endDate override. The OTE editor
 * owns all date math and id suggestion client-side; this only avoids
 * repeating the shared template once per occurrence on the wire (see
 * apps/editor/src/lib/links.ts's recurringTemplateIssueBody).
 */
function parseRecurringTemplateBlock(obj, label) {
  const { template, occurrences } = obj;
  if (typeof template !== "object" || template === null || Array.isArray(template)) {
    throw new IssueToPrError(`${capitalize(label)} is missing a "template" object`, [
      'A recurring-template block needs a `template` object with the fields shared by every occurrence.',
    ]);
  }
  if (!Array.isArray(occurrences) || occurrences.length === 0) {
    throw new IssueToPrError(`${capitalize(label)} is missing a non-empty "occurrences" array`, [
      'A recurring-template block needs an `occurrences` array with at least one entry.',
    ]);
  }
  return occurrences.map((occ, i) => {
    const occLabel = `${label}, occurrence ${i + 1} of ${occurrences.length}`;
    if (typeof occ !== "object" || occ === null || Array.isArray(occ)) {
      throw new IssueToPrError(`${capitalize(occLabel)} is not a JSON object`, [
        "Each entry in `occurrences` must be an object overriding at least `startDate`.",
      ]);
    }
    const merged = { ...template, ...occ };
    assertValidEvent(merged, occLabel);
    return { event: merged, slug: deriveSlug(merged, occLabel) };
  });
}

function assertValidPatchObject(patch, label, blockLabel) {
  if (typeof patch !== "object" || patch === null || Array.isArray(patch)) {
    throw new IssueToPrError(`${capitalize(label)} is missing a "patch" object`, [
      `A ${blockLabel} block needs a \`patch\` object — the fields to change, with \`null\` for any field to remove.`,
    ]);
  }
}

/**
 * Structural validation only for a `{_oteBatchMode: "patch", slug, patch}`
 * block — returns `{slug, patch, label}`, an operation to apply later
 * (see resolvePatchOps). Deferred, rather than reading/merging the file
 * right here, so a "shared-patch" block targeting the same slug (see below)
 * can be merged onto the same read instead of racing/duplicating it.
 */
function parsePatchBlock(obj, label) {
  const { slug, patch } = obj;
  if (typeof slug !== "string" || !SLUG_RE.test(slug)) {
    throw new IssueToPrError(`${capitalize(label)} is missing a valid "slug"`, [
      'A patch block needs a `slug` string matching `[A-Za-z0-9._-]+`, naming the `events/<slug>.json` file to update.',
    ]);
  }
  assertValidPatchObject(patch, label, "patch");
  return [{ slug, patch, label }];
}

/**
 * Structural validation for a `{_oteBatchMode: "shared-patch", slugs,
 * patch}` block — the same `patch` applied to every file in `slugs`.
 * Returns one `{slug, patch, label}` operation per slug, same shape as
 * parsePatchBlock's single result, so both feed the same resolvePatchOps
 * grouping/merging step uniformly.
 */
function parseSharedPatchBlock(obj, label) {
  const { slugs, patch } = obj;
  if (!Array.isArray(slugs) || slugs.length === 0) {
    throw new IssueToPrError(`${capitalize(label)} is missing a non-empty "slugs" array`, [
      'A shared-patch block needs a `slugs` array naming every `events/<slug>.json` file the patch applies to.',
    ]);
  }
  assertValidPatchObject(patch, label, "shared-patch");
  return slugs.map((slug, i) => {
    const slugLabel = `${label}, slug ${i + 1} of ${slugs.length}`;
    if (typeof slug !== "string" || !SLUG_RE.test(slug)) {
      throw new IssueToPrError(`${capitalize(slugLabel)} is not a valid slug`, [
        `Got \`${JSON.stringify(slug)}\` — expected a string matching \`[A-Za-z0-9._-]+\`.`,
      ]);
    }
    return { slug, patch, label: slugLabel };
  });
}

/**
 * Applies every `{slug, patch, label}` operation from "patch"/"shared-patch"
 * blocks, grouped by slug: each target file is read exactly once, then
 * every operation for that slug is merged onto it in order (a `null` value
 * deletes that key; later operations win over earlier ones for the same
 * key), and the final result is validated once. This is what lets a
 * "shared-patch" block (a value common to several files) and a "patch"
 * block (that one file's own extra change, e.g. a date override) both
 * target the same slug in one issue without colliding as a "duplicate
 * filename" — they're contributions to one merge, not two competing files.
 * Errors loudly if a target file doesn't exist: patch mode only updates an
 * existing event, it can never create one (use a complete event JSON block
 * for that).
 */
function resolvePatchOps(ops, repoRoot) {
  const bySlug = new Map();
  for (const op of ops) {
    const existing = bySlug.get(op.slug);
    if (existing) existing.push(op);
    else bySlug.set(op.slug, [op]);
  }
  const results = [];
  for (const [slug, slugOps] of bySlug) {
    const groupLabel = slugOps.map((op) => op.label).join(" + ");
    const filePath = join(repoRoot, "events", `${slug}.json`);
    if (!existsSync(filePath)) {
      throw new IssueToPrError(`${capitalize(groupLabel)} patches a file that doesn't exist`, [
        `\`events/${slug}.json\` was not found.`,
        "A patch block can only update an existing event — use a complete event JSON block to create a new one.",
      ]);
    }
    let merged;
    try {
      merged = JSON.parse(readFileSync(filePath, "utf8"));
    } catch (error) {
      throw new IssueToPrError(`${capitalize(groupLabel)} targets an unreadable file`, [
        `\`events/${slug}.json\` could not be parsed: ${error.message}`,
      ]);
    }
    for (const op of slugOps) {
      for (const [key, value] of Object.entries(op.patch)) {
        if (value === null) delete merged[key];
        else merged[key] = value;
      }
    }
    assertValidEvent(merged, groupLabel);
    results.push({ event: merged, slug });
  }
  return results;
}

/**
 * Parses one fenced block into either full `{event, slug}` results (a plain
 * event object or a "recurring-template" block) or `{slug, patch, label}`
 * operations (a "patch"/"shared-patch" block, deferred — see
 * resolvePatchOps) — tagged so parseIssueBody can route each to the right
 * place. A plain event object (no `_oteBatchMode`) behaves exactly as
 * before — one block, one result — so this stays additive, not a breaking
 * change for legacy or hand-authored issues.
 */
function parseOneBlock(text, index, total) {
  const label = total > 1 ? `block ${index} of ${total}` : "the event JSON";
  let obj;
  try {
    obj = JSON.parse(text);
  } catch (error) {
    throw new IssueToPrError(`${capitalize(label)} does not parse`, [
      "```",
      String(error.message),
      "```",
    ]);
  }
  if (obj && typeof obj === "object" && !Array.isArray(obj) && typeof obj._oteBatchMode === "string") {
    if (obj._oteBatchMode === "recurring-template") {
      return { kind: "events", items: parseRecurringTemplateBlock(obj, label) };
    }
    if (obj._oteBatchMode === "patch") return { kind: "patchOps", items: parsePatchBlock(obj, label) };
    if (obj._oteBatchMode === "shared-patch") {
      return { kind: "patchOps", items: parseSharedPatchBlock(obj, label) };
    }
    throw new IssueToPrError(`${capitalize(label)} has an unrecognized "_oteBatchMode" value`, [
      `Got \`${JSON.stringify(obj._oteBatchMode)}\`.`,
    ]);
  }
  assertValidEvent(obj, label);
  return { kind: "events", items: [{ event: obj, slug: deriveSlug(obj, label) }] };
}

/**
 * Parses, validates, and derives a filename for every fenced block in an
 * issue body. Fails on the first problem — no partial results, so an issue
 * with 23 good events and 1 bad one opens no PR at all rather than
 * silently dropping the bad one (never invent, never partially publish).
 */
export function parseIssueBody(body, { repoRoot = process.cwd() } = {}) {
  const blocks = extractFencedBlocks(body);
  if (blocks.length === 0) {
    throw new IssueToPrError("No event JSON found in this issue", [
      "The issue body must contain at least one event as a fenced code",
      "block (<code>```json … ```</code>). The OTE editor's **Propose",
      "change** button generates the issue in the right shape.",
    ]);
  }
  const parsed = blocks.map((text, i) => parseOneBlock(text, i + 1, blocks.length));
  const patchOps = parsed.filter((p) => p.kind === "patchOps").flatMap((p) => p.items);
  const patchResultBySlug = new Map(
    (patchOps.length > 0 ? resolvePatchOps(patchOps, repoRoot) : []).map((r) => [r.slug, r]),
  );
  // Preserve the issue's own block order — a slug patched by several blocks
  // (a shared-patch block plus that file's own extra "patch" block, say)
  // takes the position of whichever referenced it first.
  const results = [];
  const emittedSlugs = new Set();
  for (const block of parsed) {
    if (block.kind === "events") {
      results.push(...block.items);
      continue;
    }
    for (const op of block.items) {
      if (emittedSlugs.has(op.slug)) continue;
      emittedSlugs.add(op.slug);
      results.push(patchResultBySlug.get(op.slug));
    }
  }
  const slugs = results.map((r) => r.slug);
  const duplicate = slugs.find((slug, i) => slugs.indexOf(slug) !== i);
  if (duplicate !== undefined) {
    throw new IssueToPrError("Duplicate filename across events in this issue", [
      `More than one event resolves to \`events/${duplicate}.json\`.`,
      "Give each event a distinct id or name so their filenames don't collide.",
    ]);
  }
  return results;
}

// --- opt-in local image copies -------------------------------------------
//
// The OTE editor's image repeater has a "save a local copy" checkbox
// (apps/editor/src/ui/form.ts) that, when checked, adds a transient
// `_localizeImages` array to the event JSON in the issue body — a subset
// of `image` URLs the organizer confirmed they have the rights to host.
// localizeEventImages fetches each one, commits it under assets/<slug>/,
// and rewrites the event's image URL to point at it — never blocking the
// PR: a fetch failure just leaves that image as the original external
// link plus a warning, same as any other "connector never invents data"
// fallback in this repo.
//
// The issue author is anonymous and untrusted (that's the whole point of
// the propose-change flow), so every fetched URL is adversarial input:
// https-only, a capped number of manually-followed redirects (each
// re-checked), a DNS lookup rejecting private/loopback/link-local
// targets (defense in depth against SSRF, including cloud metadata
// endpoints), a byte cap, and a timeout.

const EXTENSION_BY_MIME = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/gif": "gif",
  "image/webp": "webp",
  "image/svg+xml": "svg",
  "image/avif": "avif",
};
const KNOWN_EXTENSIONS = new Set(["jpg", "jpeg", "png", "gif", "webp", "svg", "avif"]);

/** True for IPv4/IPv6 addresses in a loopback, link-local, or private range. */
export function isPrivateIp(ip) {
  if (net.isIPv4(ip)) {
    const [a, b] = ip.split(".").map(Number);
    return a === 10 || a === 127 || a === 0 || (a === 172 && b >= 16 && b <= 31) ||
      (a === 192 && b === 168) || (a === 169 && b === 254);
  }
  if (net.isIPv6(ip)) {
    const lower = ip.toLowerCase();
    if (lower === "::1" || lower === "::") return true;
    if (/^fe[89ab]/.test(lower)) return true; // fe80::/10 link-local
    if (/^f[cd]/.test(lower)) return true; // fc00::/7 unique local
    const mapped = /^::ffff:(\d+\.\d+\.\d+\.\d+)$/.exec(lower);
    if (mapped) return isPrivateIp(mapped[1]);
    return false;
  }
  return true; // not a recognizable literal IP — refuse rather than guess
}

async function assertPublicHost(hostname) {
  if (net.isIP(hostname)) {
    if (isPrivateIp(hostname)) {
      throw new Error(`refusing to fetch from private address ${hostname}`);
    }
    return;
  }
  if (hostname === "localhost") throw new Error("refusing to fetch from localhost");
  const { address } = await lookup(hostname);
  if (isPrivateIp(address)) {
    throw new Error(`refusing to fetch ${hostname} (resolves to private address ${address})`);
  }
}

function extensionFor(contentType, url) {
  const mime = (contentType || "").split(";")[0].trim().toLowerCase();
  if (EXTENSION_BY_MIME[mime]) return EXTENSION_BY_MIME[mime];
  const pathExt = /\.([a-z0-9]+)(?:[?#]|$)/i.exec(new URL(url).pathname)?.[1]?.toLowerCase();
  if (!pathExt || !KNOWN_EXTENSIONS.has(pathExt)) return null;
  return pathExt === "jpeg" ? "jpg" : pathExt;
}

/** Fetches `url`, following redirects manually (each hop re-validated) up to `maxRedirects`. */
export async function fetchImage(url, { maxBytes, timeoutMs, maxRedirects }) {
  let currentUrl = url;
  for (let hop = 0; hop <= maxRedirects; hop++) {
    const parsed = new URL(currentUrl);
    if (parsed.protocol !== "https:") {
      throw new Error(`refusing non-https URL (${parsed.protocol})`);
    }
    await assertPublicHost(parsed.hostname);
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    let response;
    try {
      response = await fetch(currentUrl, { redirect: "manual", signal: controller.signal });
    } finally {
      clearTimeout(timer);
    }
    if (response.status >= 300 && response.status < 400) {
      const location = response.headers.get("location");
      if (!location) throw new Error(`redirect with no Location header (HTTP ${response.status})`);
      currentUrl = new URL(location, currentUrl).href;
      continue;
    }
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const contentType = response.headers.get("content-type") ?? "";
    if (!contentType.toLowerCase().startsWith("image/")) {
      throw new Error(`not an image (content-type: ${contentType || "unknown"})`);
    }
    const declaredLength = Number(response.headers.get("content-length") ?? "0");
    if (declaredLength > maxBytes) throw new Error(`too large (${declaredLength} bytes)`);
    const buffer = Buffer.from(await response.arrayBuffer());
    if (buffer.byteLength > maxBytes) throw new Error(`too large (${buffer.byteLength} bytes)`);
    return { buffer, contentType };
  }
  throw new Error(`too many redirects (>${maxRedirects})`);
}

/**
 * Mutates every `{event, slug}` in `results` in place: strips
 * `_localizeImages` (always — even if empty/malformed, it must never reach
 * the committed file), and for each URL it lists, tries to download and
 * stage the matching `image` entry, rewriting its `url` to the
 * raw.githubusercontent.com path it will live at once committed. Staged
 * files are recorded as `result.assets` (`{tmpFile, repoPath}`) for the
 * workflow's shell step to copy into the checkout and `git add`.
 *
 * Never throws on a per-image failure — that image just keeps its
 * original external URL, and a message is added to the returned warnings.
 */
export async function localizeEventImages(
  results,
  { owner, repo, defaultBranch, tmpDir, maxBytes = 10 * 1024 * 1024, timeoutMs = 15_000, maxRedirects = 5 },
) {
  const warnings = [];
  for (const result of results) {
    const { event, slug } = result;
    const urls = Array.isArray(event._localizeImages) ? event._localizeImages : [];
    delete event._localizeImages;
    if (urls.length === 0) continue;
    const assets = [];
    for (const url of urls) {
      if (typeof url !== "string") continue;
      const matches = (event.image ?? []).filter((entry) =>
        typeof entry === "string" ? entry === url : entry.url === url,
      );
      if (matches.length === 0) continue;
      try {
        const { buffer, contentType } = await fetchImage(url, { maxBytes, timeoutMs, maxRedirects });
        const ext = extensionFor(contentType, url);
        if (!ext) throw new Error(`unrecognized image type (content-type: ${contentType})`);
        const hash = createHash("sha256").update(url).digest("hex").slice(0, 12);
        const repoPath = `assets/${slug}/${hash}.${ext}`;
        const stagingDir = join(tmpDir, "ote-assets", slug);
        mkdirSync(stagingDir, { recursive: true });
        const tmpFile = join(stagingDir, `${hash}.${ext}`);
        writeFileSync(tmpFile, buffer);
        const newUrl = `https://raw.githubusercontent.com/${owner}/${repo}/${defaultBranch}/${repoPath}`;
        for (const entry of matches) {
          if (typeof entry === "string") {
            event.image[event.image.indexOf(entry)] = newUrl;
          } else {
            entry.url = newUrl;
          }
        }
        assets.push({ tmpFile, repoPath });
      } catch (error) {
        warnings.push(
          `Could not save a local copy of ${url} for \`events/${slug}.json\`: ${error.message}. Kept the external link.`,
        );
      }
    }
    if (assets.length > 0) result.assets = assets;
  }
  return warnings;
}

// Everything below only runs when this file is executed directly (the
// workflow step) — parseIssueBody/extractFencedBlocks/etc. above are
// exercised directly by .github/scripts/issue-to-pr.test.mjs, which imports
// this module without triggering this env/filesystem wiring.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  await main();
}

async function main() {
  const marker = process.env.OTE_COMMENT_MARKER ?? "<!-- ote-issue-to-pr -->";
  const tmp = process.env.RUNNER_TEMP ?? ".";

  function setOutputs(pairs) {
    const lines = Object.entries(pairs).map(([key, value]) => `${key}=${value}`);
    appendFileSync(process.env.GITHUB_OUTPUT, lines.join("\n") + "\n");
  }

  function reject(error) {
    const body = [
      marker,
      `### ❌ ${error.title}`,
      "",
      ...error.details,
      "",
      "Edit the issue body to fix this — validation re-runs automatically on",
      "every edit. No pull request was opened.",
    ].join("\n");
    writeFileSync(join(tmp, "ote-comment.md"), body + "\n");
    setOutputs({ valid: "false" });
  }

  const body = process.env.ISSUE_BODY ?? "";
  let results;
  try {
    results = parseIssueBody(body);
  } catch (error) {
    if (!(error instanceof IssueToPrError)) throw error;
    reject(error);
    return;
  }

  const [owner, repo] = (process.env.GH_REPO ?? "").split("/");
  const defaultBranch = process.env.DEFAULT_BRANCH || "main";
  const warnings = await localizeEventImages(results, {
    owner,
    repo,
    defaultBranch,
    tmpDir: tmp,
  });
  if (warnings.length > 0) {
    writeFileSync(join(tmp, "ote-warnings.md"), warnings.map((w) => `- ${w}`).join("\n") + "\n");
  }

  writeFileSync(join(tmp, "ote-events.json"), JSON.stringify(results, null, 2) + "\n");
  setOutputs({ valid: "true", count: String(results.length) });
}
