// Step script of the issue-to-pr.yml reusable workflow. Runs from the
// ote-tools checkout (`.ote-tools/`) after @opentechevents/validate is
// built, so validation is the exact same implementation the validate.yml
// workflow and the packages use.
//
// Reads the issue body, extracts the event JSON from EVERY fenced code
// block (one issue can propose several events at once — e.g. a recurring
// series generated by the OTE editor's "Submit all as one issue"),
// validates each against the OTE event schema and derives its
// events/<slug>.json filename. A single fenced block behaves exactly as
// before (one file) — this is additive, not a breaking change.
//
// Env in:
//   ISSUE_BODY          full issue body
//   OTE_COMMENT_MARKER  hidden marker that identifies the workflow's comment
//   RUNNER_TEMP         directory for the result files
// Outputs (GITHUB_OUTPUT):
//   valid  "true" | "false"
//   count  number of events (only when valid)
// Files (in RUNNER_TEMP):
//   ote-events.json  [{event, slug}, ...], ready to commit (only when valid)
//   ote-comment.md   issue comment body (only when invalid — the success
//                    comment is written by the workflow, it needs the PR URL)

import { appendFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { validateEventInFeed } from "../../packages/validate/dist/index.js";

// Slugs must be usable as a filename in events/ and in URLs we build.
// Mirrors apps/editor/src/lib/repo.ts (slugFromId) and
// apps/editor/src/lib/event-json.ts (suggestSlug) so the file lands where
// the editor expects it.
export const SLUG_RE = /^[A-Za-z0-9._-]+$/;
const FENCE_RE = /```[^\n]*\r?\n([\s\S]*?)\r?\n?```/g;

export function slugFromId(id) {
  if (typeof id !== "string") return null;
  let pathname;
  try {
    pathname = new URL(id).pathname;
  } catch {
    return null;
  }
  const segment = decodeURIComponent(
    pathname.split("/").filter(Boolean).at(-1) ?? "",
  );
  const slug = segment.endsWith(".json")
    ? segment.slice(0, -".json".length)
    : segment;
  return SLUG_RE.test(slug) ? slug : null;
}

export function suggestSlug(name, startDate) {
  const yearMonth = /^(\d{4}-\d{2})/.exec(startDate)?.[1];
  const kebab = String(name)
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  if (!kebab) return null;
  return yearMonth ? `${yearMonth}-${kebab}` : kebab;
}

/** Every fenced code block's inner text, in document order. */
export function extractFencedBlocks(body) {
  return [...body.matchAll(FENCE_RE)].map((m) => m[1]);
}

/** Thrown by parseIssueBody on the first problem — title + Markdown detail lines for the rejection comment. */
export class IssueToPrError extends Error {
  constructor(title, details) {
    super(title);
    this.title = title;
    this.details = details;
  }
}

function parseOneBlock(text, index, total) {
  const label = total > 1 ? `block ${index} of ${total}` : "the event JSON";
  let event;
  try {
    event = JSON.parse(text);
  } catch (error) {
    throw new IssueToPrError(`${label[0].toUpperCase()}${label.slice(1)} does not parse`, [
      "```",
      String(error.message),
      "```",
    ]);
  }
  // Feed context, not standalone: events/<slug>.json is a feed fragment that
  // inherits specVersion and license from the feed (same rules build-feed
  // --check applies — the editor deliberately omits both fields).
  const result = validateEventInFeed(event);
  if (!result.valid) {
    throw new IssueToPrError(
      `${label[0].toUpperCase()}${label.slice(1)} is not valid against the OTE event schema`,
      result.errors.map((e) => `- \`${e.path}\` — ${e.message}`),
    );
  }
  const slug = slugFromId(event.id) ?? suggestSlug(event.name, event.startDate);
  if (!slug) {
    throw new IssueToPrError(`Cannot derive a filename for ${label}`, [
      "The event is valid, but neither its `id` (last path segment) nor its",
      "`name` yields a filename-safe slug for `events/<slug>.json`.",
      "Give the `id` a final path segment matching `[A-Za-z0-9._-]+`.",
    ]);
  }
  return { event, slug };
}

/**
 * Parses, validates, and derives a filename for every fenced block in an
 * issue body. Fails on the first problem — no partial results, so an issue
 * with 23 good events and 1 bad one opens no PR at all rather than
 * silently dropping the bad one (never invent, never partially publish).
 */
export function parseIssueBody(body) {
  const blocks = extractFencedBlocks(body);
  if (blocks.length === 0) {
    throw new IssueToPrError("No event JSON found in this issue", [
      "The issue body must contain at least one event as a fenced code",
      "block (<code>```json … ```</code>). The OTE editor's **Propose",
      "change** button generates the issue in the right shape.",
    ]);
  }
  const results = blocks.map((text, i) => parseOneBlock(text, i + 1, blocks.length));
  const slugs = results.map((r) => r.slug);
  const duplicate = slugs.find((slug, i) => slugs.indexOf(slug) !== i);
  if (duplicate !== undefined) {
    throw new IssueToPrError("Duplicate filename across events in this issue", [
      `More than one event resolves to \`events/${duplicate}.json\`.`,
      "Give each event a distinct id or name so their filenames don't collide.",
    ]);
  }
  return results;
}

// Everything below only runs when this file is executed directly (the
// workflow step) — parseIssueBody/extractFencedBlocks/etc. above are
// exercised directly by .github/scripts/issue-to-pr.test.mjs, which imports
// this module without triggering this env/filesystem wiring.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}

function main() {
  const marker = process.env.OTE_COMMENT_MARKER ?? "<!-- ote-issue-to-pr -->";
  const tmp = process.env.RUNNER_TEMP ?? ".";

  function setOutputs(pairs) {
    const lines = Object.entries(pairs).map(([key, value]) => `${key}=${value}`);
    appendFileSync(process.env.GITHUB_OUTPUT, lines.join("\n") + "\n");
  }

  function reject(error) {
    const body = [
      marker,
      `### ❌ ${error.title}`,
      "",
      ...error.details,
      "",
      "Edit the issue body to fix this — validation re-runs automatically on",
      "every edit. No pull request was opened.",
    ].join("\n");
    writeFileSync(join(tmp, "ote-comment.md"), body + "\n");
    setOutputs({ valid: "false" });
  }

  const body = process.env.ISSUE_BODY ?? "";
  let results;
  try {
    results = parseIssueBody(body);
  } catch (error) {
    if (!(error instanceof IssueToPrError)) throw error;
    reject(error);
    return;
  }
  writeFileSync(join(tmp, "ote-events.json"), JSON.stringify(results, null, 2) + "\n");
  setOutputs({ valid: "true", count: String(results.length) });
}
