/**
 * Writes `src/lib/icons.generated.ts` from the icon dependencies.
 *
 * Generated rather than hand-copied for the same reason `packages/validate`
 * embeds the schema with `pnpm gen`: the path data is upstream's, a typo in it
 * is invisible until it renders wrong, and an upgrade should be a regeneration
 * and a diff rather than a manual transcription. `test/icons.test.ts` imports
 * the two builders below and fails if the committed file has drifted from the
 * installed dependency.
 *
 * The output is committed so neither the build nor the test run needs the icon
 * packages to be resolvable at runtime — they stay devDependencies.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import * as simpleIcons from "simple-icons";

import { BRAND_ICONS, UI_ICONS } from "./icon-manifest.mjs";

const appDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(appDir, "src/lib/icons.generated.ts");

/** simple-icons exports `siMeetup` for the slug `meetup`. */
function simpleIconExport(slug) {
  return `si${slug.charAt(0).toUpperCase()}${slug.slice(1)}`;
}

export function brandIconData() {
  const entries = [];
  for (const [name, slug] of Object.entries(BRAND_ICONS)) {
    const icon = simpleIcons[simpleIconExport(slug)];
    // simple-icons drops marks over time on trademark grounds. Failing here
    // is the point: the alternative is a destination quietly losing its logo.
    if (!icon) throw new Error(`simple-icons has no icon for "${slug}"`);
    entries.push([name, { title: icon.title, hex: `#${icon.hex}`, path: icon.path }]);
  }
  return Object.fromEntries(entries);
}

/**
 * Lucide ships whole `<svg>` documents; we only want what goes inside, since
 * the app supplies its own sizing and stroke attributes.
 */
function lucideInner(name) {
  const file = join(appDir, "node_modules/lucide-static/icons", `${name}.svg`);
  const svg = readFileSync(file, "utf8");
  const inner = svg.slice(svg.indexOf(">", svg.indexOf("<svg")) + 1, svg.lastIndexOf("</svg>"));
  return inner.replace(/\s+/g, " ").trim();
}

export function uiIconData() {
  return Object.fromEntries(UI_ICONS.map((name) => [name, lucideInner(name)]));
}

export function render() {
  const brands = brandIconData();
  const ui = uiIconData();
  return `// GENERATED by \`pnpm gen:icons\` — do not edit by hand.
//
// Brand marks: simple-icons (CC0-1.0). Trademarks belong to their owners and
// are used here only to name the destination they point at.
// UI glyphs: Lucide (ISC), https://lucide.dev.
//
// Add or remove names in tools/icon-manifest.mjs, then re-run the script.

export interface BrandIcon {
  title: string;
  /** The brand's own colour, used to tint the tile — never to fill the mark. */
  hex: string;
  /** A single \`d\` attribute, drawn in a 24-unit box. */
  path: string;
}

export const BRAND_ICONS: Record<string, BrandIcon> = ${JSON.stringify(brands, null, 2)};

/** Inner markup of a Lucide icon, drawn in a 24-unit box with stroke 2. */
export const UI_ICONS: Record<string, string> = ${JSON.stringify(ui, null, 2)};
`;
}

// Importing this module must not write anything — the test does exactly that.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(OUT, render());
  console.log(
    `src/lib/icons.generated.ts: ${Object.keys(brandIconData()).length} brand marks, ${
      Object.keys(uiIconData()).length
    } UI glyphs`,
  );
}
